<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP</title>
    <link rel="stylesheet" href="index.css">
</head>

<body>
    <header>
        <h1>Bons de commandes</h1>
        <a href="index.php">Retourner à l'accueil</a>
    </header>
    <main>
        <section>
            <article class="customer">
                <h2><?= $customer['customerName'] ?></h2>
                <h3><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></h3>
                <p><?= $customer['addressLine1'] ?></p>
                <p><?= $customer['addressLine2'] ?></p>
                <p><?= $customer['city'] ?></p>
            </article>
            <hr>
            <table class="table">
                <caption>Bon de commande n°  <?= $_GET['orderNumber'] ?></caption>
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix Unitaire</th>
                        <th>Quantité</th>
                        <th>Prix Total</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($orderdetails as $MontantHT) : ?>
                        <tr class="tr">
                            <td><?= $MontantHT['productName'] ?></td>
                            <td><?= $MontantHT['priceEach'] ?> €</td>
                            <td><?= $MontantHT['quantityOrdered'] ?></td>
                            <td><?= $MontantHT['PrixTotal'] ?> €</td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr class="tr">
                        <th>Montant Total HT</th>
                        <th><?= round($Montant['MontantTotalHT'], 2) ?></th>
                    </tr>
                    <tr class="tr">
                        <th>TVA (20 %)</th>
                        <th class="money"><?= round($Montant['TVA'], 2) ?> €</th>
                    </tr>
                    <tr class="tr">
                        <th>Montant Total TTC</th>
                        <th class="money"><?= round($Montant['MontantTTC'], 2)  ?> €</th>
                    </tr>
                </tfoot>
            </table>
        </section>
    </main>
</body>

</html>